apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andrej-karpathy-skills
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gateszhangc/andrej-karpathy-skills.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: andrej-karpathy-skills
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
