apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/andrej-karpathy-skills
    newTag: 6e8059d11322c4d8405a2b048bb6ff8df586ed31
